version: '3'

services:
  app:
    build: ./
    image: app
    volumes:
      - ./:/application:cached
  nginx:
    image: nginx
    ports:
      - "7500:7500"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app